version: '3.8'

services:
  tatort-app:
    build: .
    volumes:
      - ./testfiles:/app/testfiles
      - ./output:/app/output
    entrypoint: ["python", "-m", "app.main"]
    command: ["testfiles/sample.mp4"]

